version: '3.8'
services:
  oncoinsights:
    container_name: oncoinsights
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=3000
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_DATA_SOURCE=static
    restart: unless-stopped 