version: '3.8'

services:
  oncoinsights:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public/data/insights:/usr/share/nginx/html/data/insights
    restart: unless-stopped 