# Railway-specific configuration

[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "/start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 60
healthcheckInterval = 15
startupDelay = "15s"

[environment]
PORT = "80"
REACT_APP_ENVIRONMENT = "production"
REACT_APP_VERSION = "railway-deployment" 