# Railway-specific configuration

[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30
healthcheckInterval = 10

[environment]
REACT_APP_ENVIRONMENT = "production"
REACT_APP_VERSION = "railway-deployment" 