# Railway-specific configuration

[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health.json"
healthcheckTimeout = 90

[environment]
PORT = "8080"
NODE_ENV = "production"
npm_config_legacy_peer_deps = "true"
REACT_APP_ENVIRONMENT = "production" 