# Railway-specific configuration

[build]
builder = "dockerfile"
dockerfile = "oncology-insights/Dockerfile"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 10

[environment]
REACT_APP_ENVIRONMENT = "production"
REACT_APP_VERSION = "railway-deployment" 