# Railway-specific configuration

[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 10

[nixpacks]
nodejs-version = "18"

[environment]
REACT_APP_ENVIRONMENT = "production"
REACT_APP_VERSION = "railway-deployment" 