apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncology-insights
  labels:
    app: oncology-insights
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oncology-insights
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: oncology-insights
    spec:
      containers:
      - name: oncology-insights
        image: ${DOCKER_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: NODE_ENV
          value: "production"
      imagePullSecrets:
      - name: regcred 