[build]
builder = "nixpacks"
buildCommand = "npm run build"
nixpacksVersion = "1.17.0"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 10
healthcheckInterval = 30

[service]
internal_port = 3000
port = 3000

[phases.setup]
aptPkgs = ["nginx"]

[phases.build]
nixPkgs = ["nodejs_18", "nginx", "busybox"]
cmds = [
  "node scripts/create-placeholder-images.js || echo 'No placeholder script found, skipping'",
  "node scripts/verify-dependencies.js || echo 'No verify script found, skipping'",
  "npm run build"
]

[phases.deploy]
cmds = [
  "mkdir -p /app/build",
  "cp -r /app/build /var/www/html",
  "cp -r /app/public/data /var/www/html/data || echo 'No data found, skipping'",
  "echo '/* /index.html 200' > /var/www/html/_redirects",
  "echo '{\"root\":\"/var/www/html\",\"routes\":{\"/**\":\"index.html\"}}' > /var/www/html/static.json",
  "node scripts/prepare-deploy.js || echo 'No prepare-deploy script found, skipping'",
  "node scripts/post-deployment.js || echo 'No post-deployment script found, skipping'"
]

[phases.start]
cmd = "npx serve -s build"

[phases.cleanup]
cmds = ["echo 'Cleanup phase executed'"]

[variables]
NODE_ENV = "production"
SERVE_PORT = "3000" 